### PR TITLE
Add screenshot sensor

### PR DESCRIPTION
**Pull request by denisabt**
As per one ticket I found, I've added a screenshot Sensor, currently only supporting Screen 0, but including working MQTT discovery and correct parsing by Home Assistant to display the screen capture as image in Lovelace UI.

image

### CODE REVIEW

**Comment by LAB02-Admin** [comment]
Could you please integrate the new `FriendlyName` attribute in `HASS.Agent/Settings/StoredSensors.cs` to resolve the merging conflict? You can use the current main branch of the staging repo.

**Comment by denisabt** [comment]
@LAB02-Admin I have updated my PR with the latest changes on main successfully. The PR should now be mergable.

**Comment by martydingo** [comment]
When will this be merged?

**Comment by manonstreet** [comment]
@denisabt can you please help to create a PR for this awesome update into amadeo-alex's [fork](https://github.com/amadeo-alex/HASS.Agent) incorporating all the latest PR's?  Thanks!

**Comment by amadeo-alex** [comment]
@denisabt if you don't mind I'll integrate the idea of screenshot sensor with the fork we're maintaining :)

**Comment by denisabt** [comment]
@amadeo-alex  - sure, go for it. if you need help or if I should merge, let me know. A reference to me/my code would be appreciated. :-)

**Comment by manonstreet** [comment]
@amadeo-alex do you have an approximate timeframe for this feature to be incorporated?

**Comment by amadeo-alex** [comment]
> @amadeo-alex do you have an approximate timeframe for this feature to be incorporated?

I plan to work on this today, should be merged into the dev branch of the fork today (no promises for today on the beta3 release including this tho :D)

**Comment by denisabt** [comment]
If I can help, or also for future feature requests (I am sure there will be bugs or things to improve on my branch), let me know  @amadeo-alex

**Comment by manonstreet** [comment]
Thanks @amadeo-alex!  I see feature was incorporated into the development 2.1.0 branch.  Unfortunately I was unable to successfully compile that branch (the shared library and satellite were ok, but not hass.agent).  I'm sure it's something I am doing wrong.

Is the plan still to incorporate the feature into 2.0.1 beta 3, or will be only be available in 2.1.0?

**Comment by amadeo-alex** [comment]
@manonstreet you can drop on the fork's discord so that we can discuss the compiling issue https://discord.gg/sJrDzwH6
In the meantime the 2.1.0-beta1 should be out in one or two days (hopefully :D) - I want to track down one MQTT bug before that but if not done within one-two days, I'll just release is as part of 2.1.0-beta2.

**Comment by manonstreet** [comment]
@amadeo-alex sorry, discord invite expired. Can you send another?

**Comment by amadeo-alex** [comment]
> @amadeo-alex sorry, discord invite expired. Can you send another?

Yup, here you go https://discord.com/invite/B3H5qyzK

**Comment by manonstreet** [comment]
The screenshot sensor in the 2.1.0 build works 🥳

**Comment by Bluscream** [comment]
Can we have this implemented?

**Pull request closed without merging**
